FROM docker/dev-environments-default:stable-1
USER 1000:1000
# RUN mkdir /home/vscode/project
# WORKDIR /home/vscode/project
ENTRYPOINT sleep infinity
# FROM node:alpine
# RUN npm i -g local-web-server
# COPY ./index.html ./index.html
# CMD ws