name: crowd-security-pensforeveryoneinc
version: "2.1"
services:
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    restart: always
    ports:
      - 8000:8000
    container_name: crowd-security-pensforeveryoneinc-app
    volumes_from:
      - vscode:rw
  vscode:
    build:
      context: .
      dockerfile: vscode.Dockerfile
    restart: always
    container_name: crowd-security-pensforeveryoneinc-vscode